icons:
	# TODO compress images, they are quite big, especially icon196, which is default meta tag icon
# see file:///home/freddy/mozilla/unicode-text-convert/mozfreddyb.github.io_2016-12-06_15-40-09.report.html
	convert icon256x256.png -scale 16x16   ../favicon.ico
	convert icon256x256.png -scale 128x128 tmp; pngcrush tmp icon128x128.png; rm tmp;
	convert icon256x256.png -scale 144x144 tmp; pngcrush tmp icon144x144.png; rm tmp;
	convert icon256x256.png -scale 152x152 tmp; pngcrush tmp icon152x152.png; rm tmp;
	convert icon256x256.png -scale 180x186 tmp; pngcrush tmp icon180x180.png; rm tmp;
	convert icon256x256.png -scale 192x192 tmp; pngcrush tmp icon192x192.png; rm tmp;
	convert icon256x256.png -scale 196x196 tmp; pngcrush tmp icon196x196.png; rm tmp;
	convert icon256x256.png -scale 180x186 tmp; pngcrush tmp icon180x180.png; rm tmp;
